name: Build SPT Node Server

on:
  push:
    branches:
      - 'master'
    paths:
      - 'build_server.ps1'
      - '.github/workflows/node-server.yml'
  pull_request:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  job1:
    name: Build SPT Node Server
    strategy:
      fail-fast: false
      matrix:
        m: 
          [
            # {
            #   branch: "3.10.5-DEV", 
            #   node: 20
            # },
            {
              branch: "3.11.x-dev",
              node: 22
            }
          ]
        os: 
          [
            {
              runs-on: "ubuntu-latest",
              os: "win32",
              arch: "x64",
              flags: "-NoZip",
              zip: false
            },
            {
              runs-on: "ubuntu-latest",
              os: "linux",
              arch: "x64",
              flags: "",
              zip: true
            },
            {
              runs-on: "ubuntu-24.04-arm",
              os: "linux",
              arch: "arm64",
              flags: "",
              zip: true
            }
          ]
        dbg: ["", "-Release"]
    
    runs-on: ${{matrix.os.runs-on}}
    
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.m.node}}

      - name: Build SPT Server
        id: build
        shell: pwsh
        run: ./build_server.ps1 -Overwrite -Branch ${{matrix.m.branch}} -Os ${{matrix.os.os}} -Arch ${{matrix.os.arm64}} ${{matrix.dbg}} ${{matrix.os.flags}}

      - uses: actions/upload-artifact@v4
        if: ${{! matrix.os.zip}}
        with:
          name: ${{ steps.build.outputs.ZIP_NAME }}
          path: './Server/project/build/*'
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 3
          compression-level: 9      

      - uses: actions/upload-artifact@v4
        if: ${{matrix.os.zip}}
        with:
          name: ${{ steps.build.outputs.ZIP_NAME }}
          path: './Server/${{ steps.build.outputs.ZIP_NAME }}'
          include-hidden-files: true
          if-no-files-found: error
          retention-days: 3
          compression-level: 0